In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
import warnings
warnings.filterwarnings("ignore")

In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [3]:
Auto=pd.read_csv("Automobile_data.csv")
Auto

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,13495
1,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,16500
2,1,?,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154,19,26,16500
3,2,164,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102,24,30,13950
4,2,164,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114,23,28,16845
201,-1,95,volvo,gas,sedan,rwd,front,68.8,55.5,ohc,141,160,19,25,19045
202,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohcv,173,134,18,23,21485
203,-1,95,volvo,diesel,sedan,rwd,front,68.9,55.5,ohc,145,106,26,27,22470
204,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114,19,25,22625

In [4]:
Auto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   body-style         205 non-null    object
 5   drive-wheels       205 non-null    object
 6   engine-location    205 non-null    object
 7   width              205 non-null    float64
 8   height             205 non-null    float64
 9   engine-type        205 non-null    object
 10  engine-size        205 non-null    int64
 11  horsepower         205 non-null    object
 12  city-mpg           205 non-null    int64
 13  highway-mpg        205 non-null    int64
 14  price              205 non-null    int64
dtypes: float64(2), int64(5), object(8)
memory usage: 24.2+ KB

In [5]:
Auto["normalized-losses"].replace("?",np.nan,inplace=True)
Auto["horsepower"].replace("?",np.nan,inplace=True)
Auto

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,13495
1,3,NaN,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,16500
2,1,NaN,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154,19,26,16500
3,2,164,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102,24,30,13950
4,2,164,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114,23,28,16845
201,-1,95,volvo,gas,sedan,rwd,front,68.8,55.5,ohc,141,160,19,25,19045
202,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohcv,173,134,18,23,21485
203,-1,95,volvo,diesel,sedan,rwd,front,68.9,55.5,ohc,145,106,26,27,22470
204,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114,19,25,22625

In [6]:
Auto.isnull().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
body-style            0
drive-wheels          0
engine-location       0
width                 0
height                0
engine-type           0
engine-size           0
horsepower            2
city-mpg              0
highway-mpg           0
price                 0
dtype: int64

In [7]:
Auto["normalized-losses"]=Auto["normalized-losses"].astype("float64")
Auto["horsepower"]=Auto["horsepower"].astype("float64")
Auto

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111.0,21,27,13495
1,3,NaN,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111.0,21,27,16500
2,1,NaN,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154.0,19,26,16500
3,2,164.0,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102.0,24,30,13950
4,2,164.0,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115.0,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114.0,23,28,16845
201,-1,95.0,volvo,gas,sedan,rwd,front,68.8,55.5,ohc,141,160.0,19,25,19045
202,-1,95.0,volvo,gas,sedan,rwd,front,68.9,55.5,ohcv,173,134.0,18,23,21485
203,-1,95.0,volvo,diesel,sedan,rwd,front,68.9,55.5,ohc,145,106.0,26,27,22470
204,-1,95.0,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114.0,19,25,22625

In [8]:
Auto.describe()

,symboling,normalized-losses,width,height,engine-size,horsepower,city-mpg,highway-mpg,price
count,205.000000,164.000000,205.000000,205.000000,205.000000,203.000000,205.000000,205.000000,205.000000
mean,0.834146,122.000000,65.907805,53.724878,126.907317,104.256158,25.219512,30.751220,13227.478049
std,1.245307,35.442168,2.145204,2.443522,41.642693,39.714369,6.542142,6.886443,7902.651615
min,-2.000000,65.000000,60.300000,47.800000,61.000000,48.000000,13.000000,16.000000,5118.000000
25%,0.000000,94.000000,64.100000,52.000000,97.000000,70.000000,19.000000,25.000000,7788.000000
50%,1.000000,115.000000,65.500000,54.100000,120.000000,95.000000,24.000000,30.000000,10345.000000
75%,2.000000,150.000000,66.900000,55.500000,141.000000,116.000000,30.000000,34.000000,16500.000000
max,3.000000,256.000000,72.300000,59.800000,326.000000,288.000000,49.000000,54.000000,45400.000000

In [9]:
Auto["normalized-losses"].fillna(122,inplace=True)
Auto["horsepower"].fillna(104,inplace=True)
Auto

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,122.0,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111.0,21,27,13495
1,3,122.0,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111.0,21,27,16500
2,1,122.0,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154.0,19,26,16500
3,2,164.0,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102.0,24,30,13950
4,2,164.0,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115.0,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114.0,23,28,16845
201,-1,95.0,volvo,gas,sedan,rwd,front,68.8,55.5,ohc,141,160.0,19,25,19045
202,-1,95.0,volvo,gas,sedan,rwd,front,68.9,55.5,ohcv,173,134.0,18,23,21485
203,-1,95.0,volvo,diesel,sedan,rwd,front,68.9,55.5,ohc,145,106.0,26,27,22470
204,-1,95.0,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114.0,19,25,22625

In [10]:
Auto.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
body-style           0
drive-wheels         0
engine-location      0
width                0
height               0
engine-type          0
engine-size          0
horsepower           0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [11]:
Auto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    float64
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   body-style         205 non-null    object
 5   drive-wheels       205 non-null    object
 6   engine-location    205 non-null    object
 7   width              205 non-null    float64
 8   height             205 non-null    float64
 9   engine-type        205 non-null    object
 10  engine-size        205 non-null    int64
 11  horsepower         205 non-null    float64
 12  city-mpg           205 non-null    int64
 13  highway-mpg        205 non-null    int64
 14  price              205 non-null    int64
dtypes: float64(4), int64(5), object(6)
memory usage: 24.2+ KB

In [12]:
Auto_num=Auto.select_dtypes(["float64","int64"])
Auto_num

,symboling,normalized-losses,width,height,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,122.0,64.1,48.8,130,111.0,21,27,13495
1,3,122.0,64.1,48.8,130,111.0,21,27,16500
2,1,122.0,65.5,52.4,152,154.0,19,26,16500
3,2,164.0,66.2,54.3,109,102.0,24,30,13950
4,2,164.0,66.4,54.3,136,115.0,18,22,17450
...,...,...,...,...,...,...,...,...,...
200,-1,95.0,68.9,55.5,141,114.0,23,28,16845
201,-1,95.0,68.8,55.5,141,160.0,19,25,19045
202,-1,95.0,68.9,55.5,173,134.0,18,23,21485
203,-1,95.0,68.9,55.5,145,106.0,26,27,22470
204,-1,95.0,68.9,55.5,141,114.0,19,25,22625

In [13]:
Auto_cat=Auto.select_dtypes(["object"])  
Auto_cat

,make,fuel-type,body-style,drive-wheels,engine-location,engine-type
0,alfa-romero,gas,convertible,rwd,front,dohc
1,alfa-romero,gas,convertible,rwd,front,dohc
2,alfa-romero,gas,hatchback,rwd,front,ohcv
3,audi,gas,sedan,fwd,front,ohc
4,audi,gas,sedan,4wd,front,ohc
...,...,...,...,...,...,...
200,volvo,gas,sedan,rwd,front,ohc
201,volvo,gas,sedan,rwd,front,ohc
202,volvo,gas,sedan,rwd,front,ohcv
203,volvo,diesel,sedan,rwd,front,ohc
204,volvo,gas,sedan,rwd,front,ohc

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
for col in Auto_cat:
    le=LabelEncoder()
    Auto_cat[col]=le.fit_transform(Auto_cat[col])

In [16]:
Auto_cat

     make  fuel-type  body-style  drive-wheels  engine-location  engine-type
0       0          1           0             2                0            0
1       0          1           0             2                0            0
2       0          1           2             2                0            5
3       1          1           3             1                0            3
4       1          1           3             0                0            3
..    ...        ...         ...           ...              ...          ...
200    21          1           3             2                0            3
201    21          1           3             2                0            3
202    21          1           3             2                0            5
203    21          0           3             2                0            3
204    21          1           3             2                0            3

[205 rows x 6 columns]

In [17]:
Auto2=pd.concat([Auto_num,Auto_cat],axis=1)

In [18]:
Auto2

,symboling,normalized-losses,width,height,engine-size,horsepower,city-mpg,highway-mpg,price,make,fuel-type,body-style,drive-wheels,engine-location,engine-type
0,3,122.0,64.1,48.8,130,111.0,21,27,13495,0,1,0,2,0,0
1,3,122.0,64.1,48.8,130,111.0,21,27,16500,0,1,0,2,0,0
2,1,122.0,65.5,52.4,152,154.0,19,26,16500,0,1,2,2,0,5
3,2,164.0,66.2,54.3,109,102.0,24,30,13950,1,1,3,1,0,3
4,2,164.0,66.4,54.3,136,115.0,18,22,17450,1,1,3,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,68.9,55.5,141,114.0,23,28,16845,21,1,3,2,0,3
201,-1,95.0,68.8,55.5,141,160.0,19,25,19045,21,1,3,2,0,3
202,-1,95.0,68.9,55.5,173,134.0,18,23,21485,21,1,3,2,0,5
203,-1,95.0,68.9,55.5,145,106.0,26,27,22470,21,0,3,2,0,3
204,-1,95.0,68.9,55.5,141,114.0,19,25,22625,21,1,3,2,0,3

In [19]:
X=Auto2.drop("price",axis=1) 
Y=Auto["price"]

In [20]:
X

,symboling,normalized-losses,width,height,engine-size,horsepower,city-mpg,highway-mpg,make,fuel-type,body-style,drive-wheels,engine-location,engine-type
0,3,122.0,64.1,48.8,130,111.0,21,27,0,1,0,2,0,0
1,3,122.0,64.1,48.8,130,111.0,21,27,0,1,0,2,0,0
2,1,122.0,65.5,52.4,152,154.0,19,26,0,1,2,2,0,5
3,2,164.0,66.2,54.3,109,102.0,24,30,1,1,3,1,0,3
4,2,164.0,66.4,54.3,136,115.0,18,22,1,1,3,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,68.9,55.5,141,114.0,23,28,21,1,3,2,0,3
201,-1,95.0,68.8,55.5,141,160.0,19,25,21,1,3,2,0,3
202,-1,95.0,68.9,55.5,173,134.0,18,23,21,1,3,2,0,5
203,-1,95.0,68.9,55.5,145,106.0,26,27,21,0,3,2,0,3
204,-1,95.0,68.9,55.5,141,114.0,19,25,21,1,3,2,0,3

In [21]:
Y

0      13495
1      16500
2      16500
3      13950
4      17450
       ...
200    16845
201    19045
202    21485
203    22470
204    22625
Name: price, Length: 205, dtype: int64

In [22]:
#TRAIN TEST SPLIT

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=1)

In [23]:
lr=LinearRegression()

In [24]:
lr.fit(X_train,Y_train)

LinearRegression()

In [25]:
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

In [26]:
y_pred=lr.predict(X_train)

In [27]:
y_pred

array([16288.78089907, 15862.95149012,  5838.85225599,  7399.90019178,
        7448.21287589,  8340.19293437, 20112.98005262, 12044.05266806,
       10881.60200688, 29477.54680554, 15851.9576196 ,  5979.02408373,
       15128.40723229, 30633.48117389,  8026.17576096, 15238.00805431,
       22671.61292865,  7399.90019178,  6876.94807402,  5437.9556886 ,
        7448.21287589, 13729.614748  , 12275.26312398, 18782.75001558,
       34471.24861641, 19788.70481388, 16081.44896613,  6000.87989708,
       10695.97649555,  9851.0277694 ,  9007.88175727, 15773.38145604,
       18782.75001558, 15020.478675  , 17614.12396185,  8686.88081574,
        6484.6612469 , 19763.98462653, 10389.77691781,  8196.42991173,
       13575.80397841,  9258.49510772, 19763.98462653,  6848.33965708,
       20937.2084722 ,  5364.90343873, 14826.45121096, 18111.27200303,
        7364.42547833,  7448.21287589,  8643.97737049, 18407.97834397,
       27392.95983622, 10345.55762394,  5854.17491501, 20831.03092752,
       13899.86889877, 13511.64073243,  3948.72693188,  6147.84196728,
       16744.44522502, 15988.33940171,  9507.81253708, 16894.36520659,
        9008.62330344,  9287.2891067 , 13821.45059837, 40253.97925028,
        7439.01928048,  7602.43163238,  9080.49746988, 19338.28809462,
       13785.97132607,  6844.49419667, 15020.478675  ,  6387.47261864,
       10525.72234478, 16044.19941486,  8366.55495137, 34471.24861641,
       14222.1000298 , 11008.24426048, 20327.37140874,  8014.32742889,
       11758.18360717, 16974.45774596,  9916.52351832, 13689.87990036,
       25576.22660256, 12227.89920997, 13899.86889877, 17448.23497351,
        8585.96761534,  7556.36394943,  6570.3566982 ,  6745.083773  ,
       10981.39614653,  6740.61084896, 13158.30338666, 11355.5707876 ,
       37002.61389786,  9791.293392  , 10715.76299512, 16075.33747737,
        5897.42889197,  4651.03678881, 16952.83948734, 17275.88926685,
       21556.6106077 , 13519.6257496 , 34641.50276718, 13511.64073243,
        9507.81253708,  6767.18367262, 13103.59509522, 13279.39857038,
       20605.61520428, 16337.09706083,  8233.03545528, 10345.55762394,
        7439.01928048, 26988.01552795, 10167.67736728,  8668.98308802,
        5752.44438399,  5654.73103393,  8229.94091489,  9077.21590059,
       19626.90027913,  7022.15463657, 17922.19147194,  6570.3566982 ,
       12044.05266806, 33195.31032033, 21070.38466345,  9557.39708456,
        9290.47451353,  7031.7043713 , 11758.18360717, 10586.07739028,
       30902.53104263,  7244.61323   , 11141.23512041])

In [28]:
y_predtest=lr.predict(X_test)

In [29]:
y_predtest

array([ 6147.84196728,  6876.94807402,  5163.80846164,  6529.79192553,
        9097.54846833, 26360.3208709 ,  7459.89768787,   878.21437887,
        5143.88900492, 13519.6257496 , 15450.93058606, 14432.82705309,
       16383.40498746, 11141.23512041, 16456.4588046 , 13899.86889877,
        7470.86479737,  8822.18660532, 10871.94645117,  7575.71466139,
       10982.72029689,  6830.52007514, 13695.70996881,  6367.03291176,
       13729.614748  ,  8822.18660532, 15020.478675  ,  6519.05582477,
        4748.75013887,  9309.72977579,  8168.71319861, 14331.47900196,
       25640.23271405, 11910.76074116, 19763.98462653,  6561.95927003,
        8169.72797695, 30668.72328963,  9815.88325511, 16913.25842105,
        6488.34658028, 20293.80388985,  7703.70101986,  8440.35823684,
        8643.97737049,  7183.2222224 , 40496.49068905,  7556.36394943,
       17202.63501848, 18961.22672644, 26165.63344538, 16952.83948734,
       21835.40214346,  6217.21846787, 13103.59509522,  7263.5879863 ,
       11008.24426048, 11228.96658854, 22671.61292865,  8338.96734938,
        9507.81253708, 11200.69411327])

In [30]:
r2_score(Y_train,y_pred)

0.8504568715278975

In [31]:
r2_score(Y_test,y_predtest)

0.7965544858354374

In [32]:
lr.score(X_train,Y_train)

0.8504568715278975

In [33]:
lr.score(X_test,Y_test)

0.7965544858354374

In [34]:
lr.coef_

array([ 4.51306786e+01,  1.53226590e+00,  7.89414119e+02,  3.62704004e+02,
        9.83648625e+01, -1.08091293e+01,  3.08067510e+02, -4.17054418e+02,
       -2.00105431e+02, -6.22733455e+02, -1.70254151e+02,  1.86861852e+03,
        1.64130546e+04,  2.83207856e+02])

In [35]:
lr.intercept_

-65023.15888168591

In [36]:
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge

In [37]:
l2=Ridge(0.01) #ALPHA VALUE IN BRACKET
l2.fit(X_train,Y_train)

Ridge(alpha=0.01)

In [38]:
l2.score(X_train,Y_train)

0.850455197935917

In [39]:
l2.score(X_test,Y_test)

0.796760582814735

In [40]:
l2.coef_

array([ 4.64916534e+01,  1.50273974e+00,  7.86277229e+02,  3.64199164e+02,
        9.83760500e+01, -1.05792338e+01,  3.07337653e+02, -4.16091219e+02,
       -2.00060315e+02, -6.30258245e+02, -1.73610998e+02,  1.86937479e+03,
        1.63207448e+04,  2.85285090e+02])

In [41]:
#RIDGE

for alpha in range(1,5):
    l2=Ridge(alpha)
    l2.fit(X_train,Y_train)
    train_score=l2.score(X_train,Y_train)
    test_score=l2.score(X_test,Y_test)
    print("Alpha:",alpha)
    print("train score:",train_score)
    print("test score:",test_score)
    print("-----------------") #0.8504568715278975
    
    #0.7965544858354374

Alpha: 1
train score: 0.8436017374447922
test score: 0.8074548621129003
-----------------
Alpha: 2
train score: 0.8356568441584948
test score: 0.811034506445969
-----------------
Alpha: 3
train score: 0.8295968895778684
test score: 0.8126999425979508
-----------------
Alpha: 4
train score: 0.825005387860624
test score: 0.8136223491977842
-----------------

In [42]:
#LASSO
l3=Lasso(1000)
l3.fit(X_train,Y_train)

Lasso(alpha=1000)

In [43]:
l3.score(X_train,Y_train)

0.7571401152224295

In [44]:
l3.score(X_test,Y_test)

0.7909667513581435

In [45]:
l3.coef_

array([   0.        ,    3.96253694,    0.        ,  276.9508172 ,
        135.33567163,   16.01223256,   -0.        , -113.00631031,
       -126.40854845,   -0.        ,   -0.        ,    0.        ,
          0.        ,    0.        ])

In [46]:
for i in range(200,500,50):
    l3=Lasso(i)
    l3.fit(X_train,Y_train)
    train_score=l3.score(X_train,Y_train)
    test_score=l3.score(X_test,Y_test)
    print("Alpha:",i)
    print("train score:",train_score)
    print("test score:",test_score)
    print("-----------------")

Alpha: 200
train score: 0.7987397299462572
test score: 0.8139303213862605
-----------------
Alpha: 250
train score: 0.7813843847982096
test score: 0.8124342984339288
-----------------
Alpha: 300
train score: 0.7770065687267561
test score: 0.8085187191032364
-----------------
Alpha: 350
train score: 0.7718323236476152
test score: 0.8036189498196697
-----------------
Alpha: 400
train score: 0.7658630149160937
test score: 0.7977371467625775
-----------------
Alpha: 450
train score: 0.7629200677655351
test score: 0.7950628309730501
-----------------

In [47]:
l3.coef_

array([   0.        ,    5.51024906,  157.28056951,  359.19442133,
        128.83961308,   17.99200885,    0.        , -104.44337584,
       -148.54953286,   -0.        ,   -0.        ,    0.        ,
          0.        ,   11.82980668])

In [48]:
#FINAL RIDGE MODEL==SELECTING ALPHA 2

l2=Ridge(alpha=2)
l2.fit(X_train,Y_train)
print(l2.score(X_test,Y_test))

0.811034506445969

In [49]:
l2.coef_

array([ 1.66481207e+02, -8.84441662e-01,  5.06205088e+02,  5.02070049e+02,
        1.00152739e+02,  1.04161416e+01,  2.44076856e+02, -3.27705725e+02,
       -1.94640409e+02, -1.13899099e+03, -4.80930429e+02,  1.88116260e+03,
        7.76063665e+03,  4.65935098e+02])

In [50]:
#FINAL LASSO MODEL==SELECTING ALPHA 200

l3=Lasso(alpha=200)
l3.fit(X_train,Y_train)
print(l3.score(X_test,Y_test))

0.8139303213862605

In [51]:
l3.coef_

array([ 0.00000000e+00,  2.07021553e+00,  3.23421219e+02,  4.69437653e+02,
        1.15549424e+02,  1.42877830e+01,  3.63171263e+01, -1.24771792e+02,
       -1.67460469e+02, -0.00000000e+00, -4.05148448e+02,  1.11235080e+03,
        2.09408607e+03,  3.05842633e+02])

In [52]:
#CROSS VALIDATION

from sklearn.model_selection import cross_val_score

In [53]:
l2_cross=cross_val_score(l2,X,Y,cv=4) #cv should be always between 3 to 5

In [54]:
l2_cross

array([0.71178047, 0.86472552, 0.37642252, 0.47023102])

In [55]:
np.mean(l2_cross) # if the mean is greater 0.5 then the algorithm is working properly

0.6057898826480451

In [56]:
l3_cross=cross_val_score(l3,X,Y,cv=4)

In [57]:
l3_cross

array([0.76561877, 0.81869964, 0.433466  , 0.44840117])

In [58]:
np.mean(l3_cross)

0.6165463980906682